---
- name: Configure Jenkins Server with Nginx proxy
  hosts: jenkins_master
  become: yes
  roles:
    - ubuntu_update
    - jenkins_master
    - nginx_reverse_proxy

- name: Jenkins worker with Nodejs, npm and Docker 
  hosts: jenkins_worker
  become: yes
  roles:
    - ubuntu_update
    - jenkins_worker
    - geerlingguy.docker