---
# Jenkins Master Installation Tasks

- name: Install OpenJDK-17 (Jenkins dependency)
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Ensure Jenkins is started and enabled
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Get Jenkins admin password from the file
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_admin_password

- name: Show Jenkins Admin Password
  debug:
    msg: "Jenkins Admin Password: {{ jenkins_admin_password.stdout }}"
