apiVersion: v1
kind: Namespace
metadata:
  name: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-local
  namespace: nginx

spec: 
  replicas: 2
  selector:
    matchLabels:
      app: nginx-local
  template:
    metadata:
      labels:
        app: nginx-local

    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
          name: nginx-port

---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-local
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: nginx-local
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000