apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-script
  labels:
    app: python-script-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-script-app
  template:
    metadata:
      labels:
        app: python-script-app
    spec:
      containers:
      - name: python-script-container
        image: sashaloven/module_2:python-script
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082" 

---

apiVersion: v1
kind: Service
metadata:
  name: python-script-service
spec:
  selector:
    app: python-script-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort
