version: '3'
services:
  app:
    build: 
      context: ./application
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "8000:8000"  # Expose the Flask app to port 8000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"  # Expose NGINX on port 8080
    volumes:
      - ./nginx_proxy/nginx.conf:/etc/nginx/conf.d/default.conf:Z  # Bind the nginx config
    user: root
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
